// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTechConnect.Contexts;

#nullable disable

namespace WebApiTechConnect.Migrations
{
    [DbContext(typeof(TechConnectContext))]
    [Migration("20241008180801_bd")]
    partial class bd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiTechConnect.Domains.Chat", b =>
                {
                    b.Property<Guid>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario2")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdChat");

                    b.HasIndex("IdUsuario1");

                    b.HasIndex("IdUsuario2");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.ChatMessage", b =>
                {
                    b.Property<Guid>("IdChatMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraEnvio")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRemetente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdChatMessage");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdRemetente");

                    b.ToTable("ChatMessage");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Comentarios", b =>
                {
                    b.Property<Guid>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPublicacao")
                        .IsRequired()
                        .HasColumnType("DATE");

                    b.Property<Guid>("IdPublicacao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdComentario");

                    b.HasIndex("IdPublicacao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Curtidas", b =>
                {
                    b.Property<Guid>("IdCurtida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPublicacao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdCurtida");

                    b.HasIndex("IdPublicacao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Curtidas");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Midia", b =>
                {
                    b.Property<Guid>("IdMidia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobStorageName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("UrlMidia")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("IdMidia");

                    b.ToTable("Midia");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Publicacoes", b =>
                {
                    b.Property<Guid>("IdPublicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataPublicacao")
                        .IsRequired()
                        .HasColumnType("DATE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdMidia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPublicacao");

                    b.HasIndex("IdMidia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Publicacoes");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Seguidores", b =>
                {
                    b.Property<Guid>("IdSeguidores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSeguido")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSeguidor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSeguidores");

                    b.HasIndex("IdSeguido");

                    b.HasIndex("IdSeguidor");

                    b.ToTable("Seguidores");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Usuarios", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("IdMidia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdMidia");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Chat", b =>
                {
                    b.HasOne("WebApiTechConnect.Domains.Usuarios", "Usuario1")
                        .WithMany()
                        .HasForeignKey("IdUsuario1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiTechConnect.Domains.Usuarios", "Usuario2")
                        .WithMany()
                        .HasForeignKey("IdUsuario2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario1");

                    b.Navigation("Usuario2");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.ChatMessage", b =>
                {
                    b.HasOne("WebApiTechConnect.Domains.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiTechConnect.Domains.Usuarios", "Remetente")
                        .WithMany()
                        .HasForeignKey("IdRemetente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Comentarios", b =>
                {
                    b.HasOne("WebApiTechConnect.Domains.Publicacoes", "Publicacoes")
                        .WithMany()
                        .HasForeignKey("IdPublicacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiTechConnect.Domains.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Curtidas", b =>
                {
                    b.HasOne("WebApiTechConnect.Domains.Publicacoes", "Publicacoes")
                        .WithMany()
                        .HasForeignKey("IdPublicacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiTechConnect.Domains.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Publicacoes", b =>
                {
                    b.HasOne("WebApiTechConnect.Domains.Midia", "Midia")
                        .WithMany()
                        .HasForeignKey("IdMidia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiTechConnect.Domains.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Seguidores", b =>
                {
                    b.HasOne("WebApiTechConnect.Domains.Usuarios", "Seguido")
                        .WithMany()
                        .HasForeignKey("IdSeguido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiTechConnect.Domains.Usuarios", "Seguidor")
                        .WithMany()
                        .HasForeignKey("IdSeguidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seguido");

                    b.Navigation("Seguidor");
                });

            modelBuilder.Entity("WebApiTechConnect.Domains.Usuarios", b =>
                {
                    b.HasOne("WebApiTechConnect.Domains.Midia", "Midia")
                        .WithMany()
                        .HasForeignKey("IdMidia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");
                });
#pragma warning restore 612, 618
        }
    }
}
